# Generated by Django 4.1.3 on 2022-12-09 16:18

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('caption', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='post_images')),
                ('post_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
