# Generated by Django 4.1.3 on 2022-12-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0004_userpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='diff_profile',
            field=models.BooleanField(default=False),
        ),
    ]
