# Generated by Django 4.1.3 on 2022-12-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0005_userpost_diff_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='diff_profile',
            field=models.CharField(max_length=50),
        ),
    ]
