# Generated by Django 4.1.3 on 2022-12-14 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0006_alter_userpost_diff_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='diff_profile',
            new_name='profile',
        ),
    ]
