# Generated by Django 4.1.3 on 2022-12-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0011_customuser_friends_alter_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(),
        ),
    ]
