# Generated by Django 4.1.3 on 2022-12-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0012_customuser_age_alter_customuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interest',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
