# Generated by Django 4.1.3 on 2022-12-21 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0013_customuser_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='interest',
        ),
        migrations.CreateModel(
            name='InterestTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
