# Generated by Django 4.1.3 on 2022-12-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0014_remove_customuser_interest_interesttags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterestTags',
            new_name='InterestTag',
        ),
    ]
