# Generated by Django 4.1.3 on 2022-12-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0015_rename_interesttags_interesttag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interesttag',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='interest',
            field=models.ManyToManyField(to='sna.interesttag'),
        ),
    ]
