# Generated by Django 4.1.3 on 2022-12-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0017_alter_interesttag_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interest',
            field=models.ManyToManyField(blank=True, to='sna.interesttag'),
        ),
    ]
