# Generated by Django 4.1.3 on 2023-01-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0023_alter_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='diff_profile',
        ),
    ]
