# Generated by Django 4.1.3 on 2023-01-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0024_remove_userpost_diff_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(upload_to='profile_images'),
        ),
    ]
