# Generated by Django 4.1.3 on 2023-01-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0025_alter_customuser_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeUserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userpost',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
