# Generated by Django 4.1.3 on 2023-01-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0028_alter_customuser_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='interest',
        ),
        migrations.DeleteModel(
            name='InterestTag',
        ),
    ]
