# Generated by Django 4.1.3 on 2023-01-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0030_commentpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeUserPost',
            new_name='LikePost',
        ),
    ]
