# Generated by Django 4.1.3 on 2023-01-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0031_rename_likeuserpost_likepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='profile',
        ),
    ]
