# Generated by Django 4.1.3 on 2023-01-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0037_alter_commentpost_post_date_alter_userpost_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='user',
            new_name='username',
        ),
    ]
