# Generated by Django 4.1.3 on 2023-01-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0038_rename_user_userpost_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentpost',
            old_name='caption',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='userpost',
            old_name='caption',
            new_name='message',
        ),
    ]
