# Generated by Django 4.1.3 on 2023-01-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0039_rename_caption_commentpost_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='value',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='username',
        ),
    ]
