# Generated by Django 4.1.3 on 2023-01-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0041_rename_message_livechatmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Chatroom',
        ),
    ]
