# Generated by Django 4.1.3 on 2023-01-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0042_rename_room_chatroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livechatmessage',
            old_name='room',
            new_name='chatroom',
        ),
    ]
