# Generated by Django 4.1.3 on 2023-01-20 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sna', '0044_alter_friendrequest_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tags',
            new_name='interests',
        ),
    ]
