# Generated by Django 4.1.3 on 2023-01-20 17:40

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('sna', '0045_rename_tags_customuser_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='interests'),
        ),
    ]
